/*Array con maestro de productos*/
const maestroProductos = [
  {
    id: "mojaveXS",
    nombre: "Mojave 5.0 R29 XS",
    categoria: "MTB",
    talle: "XS",
    precio: 80000,
  },
  {
    id: "mojaveS",
    nombre: "Mojave 5.0 R29 S",
    categoria: "MTB",
    talle: "S",
    precio: 80000,
  },
  {
    id: "mojaveM",
    nombre: "Mojave 5.0 R29 M",
    categoria: "MTB",
    talle: "M",
    precio: 80000,
  },
  {
    id: "mojaveL",
    nombre: "Mojave 5.0 R29 L",
    categoria: "MTB",
    talle: "L",
    precio: 80000,
  },
  {
    id: "mojaveXL",
    nombre: "Mojave 5.0 R29 XL",
    categoria: "MTB",
    talle: "XL",
    precio: 80000,
  },
  {
    id: "stradaXS",
    nombre: "Strada 1.0 XS",
    categoria: "Road",
    talle: "XS",
    precio: 200000,
  },
  {
    id: "stradaS",
    nombre: "Strada 1.0 S",
    categoria: "Road",
    categoria: "",
    talle: "S",
    precio: 200000,
  },
  {
    id: "stradaM",
    nombre: "Strada 1.0 M",
    categoria: "Road",
    talle: "M",
    precio: 200000,
  },
  {
    id: "stradaL",
    nombre: "Strada 1.0 L",
    categoria: "Road",
    talle: "L",
    precio: 200000,
  },
  {
    id: "stradaXL",
    nombre: "Strada 1.0 XL",
    categoria: "Road",
    talle: "XL",
    precio: 200000,
  },
  {
    id: "stradaXL",
    nombre: "Strada 1.0 XL",
    categoria: "Road",
    talle: "XL",
    precio: 200000,
  },
  {
    id: "stradaXL",
    nombre: "Strada 1.0 XL",
    categoria: "Road",
    talle: "XL",
    precio: 200000,
  },
  {
    id: "urbanXS",
    nombre: "Urban 1.0 XS",
    categoria: "Hibrida",
    talle: "XS",
    precio: 140000,
  },
  {
    id: "urbanS",
    nombre: "Urban 1.0 S",
    categoria: "Hibrida",
    talle: "S",
    precio: 140000,
  },
  {
    id: "urbanM",
    nombre: "Urban 1.0 M",
    categoria: "Hibrida",
    talle: "M",
    precio: 140000,
  },
  {
    id: "urbanL",
    nombre: "Urban 1.0 L",
    categoria: "Hibrida",
    talle: "L",
    precio: 140000,
  },
  {
    id: "urbanXL",
    nombre: "Urban 1.0 XL",
    categoria: "Hibrida",
    talle: "XL",
    precio: 140000,
  },
  {
    id: "mxr12",
    nombre: "MX Rodado 12",
    categoria: "Kids",
    talle: "12",
    precio: 40000,
  },
  {
    id: "mxr14",
    nombre: "MX Rodado 14",
    categoria: "Kids",
    talle: "14",
    precio: 40000,
  },
  {
    id: "mxr16",
    nombre: "MX Rodado 16",
    categoria: "Kids",
    talle: "16",
    precio: 40000,
  },
  {
    id: "mxr18",
    nombre: "MX Rodado 18",
    categoria: "Kids",
    talle: "18",
    precio: 50000,
  },
  {
    id: "mxr20",
    nombre: "MX Rodado 20",
    categoria: "Kids",
    talle: "20",
    precio: 50000,
  },
  {
    id: "scoutr24",
    nombre: "Scout Rodado 24",
    categoria: "Kids",
    talle: "24",
    precio: 60000,
  },
  {
    id: "scoutr26",
    nombre: "Scout Rodado 26",
    categoria: "Kids",
    talle: "26",
    precio: 60000,
  },
];
